INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
    VALUES ('Chris', 'Schefer', '1981-05-03');

INSERT INTO HOBBY (HOBBY_ID) VALUES ('SWIMMING');

INSERT INTO CONTACT_HOBBY_DETAIL(CONTACT_ID, HOBBY_ID) VALUES (1, 'SWIMMING')